version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_DB: kong
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 3

  fastapi:
    build: .
    container_name: fastapi_app
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: "postgresql+asyncpg://kong:kong@postgres_db/datos_fiscales"
    ports:
      - "8000:8000"
    command: ["python", "-m", "uvicorn", "app.app:app", "--host", "0.0.0.0", "--port", "8000"]

  kong:
    image: kong
    container_name: kong_gateway
    environment:
      KONG_DATABASE: "postgres"
      KONG_PG_HOST: postgres_db
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
      KONG_PG_DATABASE: kong
      KONG_PROXY_LISTEN: "0.0.0.0:8081, 0.0.0.0:8443"
      KONG_ADMIN_LISTEN: "0.0.0.0:9101, 0.0.0.0:8444"
    ports:
      - "8081:8081"
      - "8443:8443"
      - "9101:9101"
      - "8444:8444"
    depends_on:
      db:
        condition: service_healthy

volumes:
  pgdata: